import { useState } from 'react';
import './App.css';
import Faq from "react-faq-component";
import stepOne from './images/stepone.png';
import stepOneBuildings from './images/stepone-buildings.png';
import stepTwo from './images/steptwo.png';
import stepThree from './images/stepthree.png';
import downArrow from './images/down-arrow.png';

const data = {
    rows: [
        {
            title: "What exactly do these devices do?",
            content: <p>These devices are WiFi hotspots that boost cell carrier coverage. When a cell phone user from a partner carrier is nearby, their phone automatically connects to your hotspot. This offloads their data usage, giving them better speed and coverage.</p>,
        },
        {
            title: "How is the hotspot installed?",
            content:
                <>
                    <p>The WiFi hotspot is a small device that can be placed indoors near a window, or outdoors in a weather-proof enclosure. We handle the entire installation process for free.</p>
                    <div className='examples'>
                        <img className='example-image' src='https://cdn.discordapp.com/attachments/951232662436204605/979156620372226129/WhatsApp_Image_2022-05-25_at_8.00.21_PM.jpeg' alt="Installation example 1"></img>
                        <img className='example-image' src='https://cdn.discordapp.com/attachments/951232662436204605/994362702485008395/IMG_2830.jpg' alt="Installation example 2"></img>
                        <img className='example-image' src='https://cdn.discordapp.com/attachments/951232662436204605/1006022517607116882/123_1.jpg' alt="Installation example 3"></img>
                    </div>
                </>
        },
        {
            title: "How much does it cost to install? Does it cost me anything to run or use?",
            content: `Our service is completely free. We take care of installation and maintenance. Customers pay their cell carrier as usual, and you get paid for providing the coverage! The only thing you provide is a place to mount the device, power, and internet access.`
        },
        {
            title: "How much money can I make?",
            content: `Payment rate is determined by the location and the amount of data that is offloaded to your hotspot. We will provide you with an earnings estimate based on your location and building.`,
        },
        {
            title: "How do I get paid?",
            content: `Payment will usually be an agreed upon flat amount per month, but can also be a percentage of the revenue generated by the data offloaded. We will work with you to determine the best payment method for you.`,
        },
        {
            title: "What if my installation site doesn't have ethernet access?",
            content: `We can work with you to find a solution. We can provide a cellular modem or a powerline adapter that will provide an ethernet connection for the hotspot.`
        },
        {
            title: "I'm interested! How do I get started?",
            content:
                <form
                    action="https://formbold.com/s/3L5ko"
                    method="POST"
                    target="dummy">
                    <label>
                        Your email address:
                        <input type="email" name="email" />
                    </label>
                    <label>
                        Describe your potential location, and ask any questions you need answered:
                        <textarea name="message"></textarea>
                    </label>
                    <button type="submit">Send</button>
                </form>
        }
    ]
};

const styles = {
    bgColor: 'rgba(0,0,0,0.3)',
    titleTextColor: "#afece7",
    rowTitleColor: "#afece7",
    rowContentColor: 'white',
    arrowColor: "white",
};

const config = {
    // animate: true,
    // arrowIcon: "V",
    // tabFocus: true
};

function App() {
    let [open, setOpen] = useState(false);
    let customClass = "";
    if (open) {
        customClass = "open";
    }
    return (
        <div className="App">
            <div className="section" id="section1">
                <h1 className='headline'>
                    <span className='main-headline'>Provide better cell coverage to your community?</span> <br /> And <span className='underline'>get paid</span> for it? Yes please. <br /> Get started in 3 steps:
                </h1>
                <div className='step-list'>
                    <div className='step' id='step-one'>
                        <div className='step-image'>
                            <div className='step-top-gradient'></div>
                            <img src={stepOneBuildings} className='step-bottom' alt="Buildings illustration"></img>
                        </div>
                        <div className="step-text-parent">
                            <div id="step-number-one" className='step-number'>
                                🛠
                            </div>
                            <div className="step-text">
                                <div className="step-content">We set up</div>
                                <div className="step-content-lower">a small WiFi hotspot in your building or on your roof, for free!</div>
                            </div>
                        </div>
                    </div>
                    <div className='step' id='step-two'>
                        <div className='step-image'>
                            <img src={stepTwo} className='step-top' alt="Data transfer illustration"></img>
                        </div>
                        <div className="step-text-parent">
                            <div id="step-number-two" className='step-number'>
                                📡
                            </div>
                            <div className="step-text">
                                <div className="step-content">Customers connect</div>
                                <div className="step-content-lower">automatically to your hotspot, boosting their phone's data speed.</div>
                            </div>
                        </div>
                    </div>
                    <div className='step' id='step-three'>
                        <div className='step-image'>
                            <img src={stepThree} className='step-top' alt="Money illustration"></img>
                        </div>
                        <div className="step-text-parent">
                            <div id="step-number-three" className='step-number'>
                                💰
                            </div>
                            <div className="step-text">
                                <div className="step-content">Get rewards!</div>
                                <div className="step-content-lower">You get paid for the data that gets used on your hotspot!</div>
                            </div>
                        </div>
                    </div>

                </div>
                <div onClick={() => document.getElementById("howsItWork").scrollIntoView({ behavior: 'smooth' })} className='howsItWork' id='howsItWork'>
                    <img className='down-arrow' src={downArrow} alt="down arrow"></img>
                    How's it work?
                </div>
            </div>
            <div className="section" id='section2'>
                <Faq
                    data={data}
                    styles={styles}
                    config={config}
                />
                <iframe name="dummy" style={{ display: 'none' }}>
                </iframe>
            </div>
        </div>
    );
}

export default App;
