import { useState } from 'react';
import './App.css';
import Faq from "react-faq-component";
import stepOne from './images/stepone.png';
import stepOneBuildings from './images/stepone-buildings.png';
import stepTwo from './images/steptwo.png';
import stepThree from './images/stepthree.png';
import downArrow from './images/down-arrow.png';

const data = {
    rows: [
        {
            title: "How do I make money with this?",
            content: `You generate extra revenue just for having WiFi at your business! We partner with mobile carriers to offload their cellular traffic onto your WiFi. In return, you receive a share of the revenue generated from this service. The more people who connect, the more you can earn.`,
        },
        {
            title: "What exactly do these devices do?",
            content: <p>These devices are WiFi hotspots that boost cell carrier coverage. When a cell phone user from a partner carrier is nearby, their phone automatically connects to your hotspot. This offloads their data usage from the cellular network, giving them better speed and coverage. You earn revenue for every connection.</p>,
        },
        {
            title: "How is the hotspot installed?",
            content:
                <>
                    <p>The WiFi hotspot is a small device that can be placed indoors near a window, or outdoors in a weather-proof enclosure. We handle the entire installation process for free.</p>
                    <div className='examples'>
                        <img className='example-image' src='https://cdn.discordapp.com/attachments/1212471286891020308/1213316429269438505/IMG_0788.jpg?ex=685b62fb&is=685a117b&hm=cd01822773e3ad1697cf7ef6a0954d8347fba66832b302f6fd7733b09656a6b7&' alt="Installation example 1"></img>
                        <img className='example-image' src='https://framerusercontent.com/images/l2fnjOAqyikoHwl28RlexxVig.jpg' alt="Installation example 2"></img>
                        <img className='example-image' src='https://media.discordapp.net/attachments/1212471286891020308/1213991113824669716/IMG_1614.jpg?ex=685b3454&is=6859e2d4&hm=a6163aa0c52d87dac71190ed3aa0dce6205391d89e4581632546934084af8c3c&=&format=webp&width=1346&height=1794' alt="Installation example 3"></img>
                    </div>
                </>
        },
        {
            title: "How much does it cost to install? Does it cost me anything to run or use?",
            content: `Our service is completely free. We take care of installation and maintenance. You simply provide a place to mount the device and power to run it. In return, you earn a share of the revenue generated by the hotspot.`,
        },
        {
            title: "What do I get for hosting a device?",
            content: `You generate extra revenue for your business just by having WiFi available. If you don't already have WiFi, we can provide a free WiFi line as a side offering to enable you to participate.`,
        },
        {
            title: "What if my business doesn't have WiFi?",
            content: `No problem! We can provide a free WiFi line as a side offering so you can still participate and earn revenue.`,
        },
        {
            title: "I'm interested! How do I get started?",
            content:
                <form
                    action="https://formbold.com/s/3L5ko"
                    method="POST"
                    target="dummy"
                    onSubmit={(e) => {
                        e.preventDefault(); // Prevent default form submission
                        e.target.submit(); // Submit the form
                        alert("Thank you! Your message has been sent."); // Show confirmation popup
                    }}
                >
                    <label>
                        Your email address:
                        <input type="email" name="email" required />
                    </label>
                    <label>
                        Describe your potential location, and ask any questions you need answered:
                        <textarea name="message" required></textarea>
                    </label>
                    <button type="submit">Send</button>
                </form>
        }
    ]
};

const styles = {
    bgColor: 'rgba(0,0,0,0.3)',
    titleTextColor: "#afece7",
    rowTitleColor: "#afece7",
    rowContentColor: 'white',
    arrowColor: "white",
};

const config = {
    // animate: true,
    // arrowIcon: "V",
    // tabFocus: true
};

function App() {
    let [open, setOpen] = useState(false);
    let customClass = "";
    if (open) {
        customClass = "open";
    }
    return (
        <div className="App">
            <div className="section" id="section1">
                <h1 className='headline'>
                    <span className='main-headline'>Provide better cell coverage to your business</span> <br /> And <span className='underline'>generate extra revenue</span> just for having WiFi!<br /> Here's how you benefit:
                </h1>
                <div className='step-list'>
                    <div className='step' id='step-one'>
                        <div className='step-image'>
                            <img src={stepOne} alt="Step 1" className="step-image-icon" />
                        </div>
                        <div className="step-text-parent">
                            <div id="step-number-one" className='step-number step-emoji-mobile-hide'>
                                🛠
                            </div>
                            <div className="step-text">
                                <div className="step-content">We set up</div>
                                <div className="step-content-lower">small WiFi hotspots in your building or on your roof, for free!</div>
                            </div>
                        </div>
                    </div>
                    <div className='step' id='step-two'>
                        <div className='step-image'>
                            <img src={stepTwo} alt="Step 2" className="step-image-icon" />
                        </div>
                        <div className="step-text-parent">
                            <div id="step-number-two" className='step-number step-emoji-mobile-hide'>
                                📡
                            </div>
                            <div className="step-text">
                                <div className="step-content">Boost cell signal</div>
                                <div className="step-content-lower">on major carriers like AT&T through our hotspots, increasing social media presence and customer satisfaction.</div>
                            </div>
                        </div>
                    </div>
                    <div className='step' id='step-three'>
                        <div className='step-image'>
                            <img src={stepThree} alt="Step 3" className="step-image-icon" />
                        </div>
                        <div className="step-text-parent">
                            <div id="step-number-three" className='step-number step-emoji-mobile-hide'>
                                📶
                            </div>
                            <div className="step-text">
                                <div className="step-content">Earn Revenue!</div>
                                <div className="step-content-lower">You get paid a share of the revenue generated by the hotspot, just for having WiFi at your business. If you don't have WiFi, we can provide it for you.</div>
                            </div>
                        </div>
                    </div>

                </div>
                <div onClick={() => document.getElementById("howsItWork").scrollIntoView({ behavior: 'smooth' })} className='howsItWork' id='howsItWork'>
                    <img className='down-arrow' src={downArrow} alt="down arrow"></img>
                    How's it work?
                </div>
            </div>
            <div className="section" id='section2'>
                <Faq
                    data={data}
                    styles={styles}
                    config={config}
                />
                <iframe name="dummy" style={{ display: 'none' }}>
                </iframe>
            </div>
        </div>
    );
}

export default App;
